-- phpMyAdmin SQL Dump
-- version 3.4.7
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Jan 17, 2012 at 09:06 AM
-- Server version: 5.1.37
-- PHP Version: 5.2.10

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `tours`
--

-- --------------------------------------------------------

--
-- Table structure for table `tour`
--

CREATE TABLE IF NOT EXISTS `tour` (
  `tourId` int(11) NOT NULL,
  `tourTitle` varchar(100) NOT NULL,
  `packageId` int(11) NOT NULL,
  `packageTitle` varchar(100) NOT NULL,
  `description` varchar(2500) NOT NULL,
  `price` int(11) NOT NULL,
  `difficulty` int(11) NOT NULL,
  `length` float NOT NULL,
  `image` varchar(100) NOT NULL,
  `link` varchar(100) NOT NULL,
  PRIMARY KEY (`tourId`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `tour`
--

INSERT INTO `tour` (`tourId`, `tourTitle`, `packageId`, `packageTitle`, `description`, `price`, `difficulty`, `length`, `image`, `link`) VALUES
(14, '2 Days Adrift the Salton Sea', 5, 'From Desert to Sea', ' The Salton Sea is saltier than the Pacific, an unusual feat for inland body of water. And even though its salinity has risen over the years, due in part to lack of outflows and pollution from agricultural runoff, it has attracted a small, but dedicated population. The sea itself offers recreational opportunities including boating, camping, off-roading, hiking, use of personal watercraft, photography and bird watching. The sea has been termed a "crown jewel of avian biodiversity," being a major resting stop on the Pacific Flyway, a migratory path for birds. 2 Days Adrift the Salton Sea includes two nights accommodations at the Bombay Beach Inn, boat rental at the Salton City Harbor, and a guided fishing tour. ', 350, 2, 2, 'map_saltonsea.gif', '\n    http://www.explorecalifornia.org/tour.php?id=14\n    '),
(26, 'A Week of Wine', 9, 'Taste of California', ' Immerse yourself in the culture and lifestyle of a California winery. Spend 5 days in your private guest villa at the Stockbridge Winery, located in scenic Sonoma. You''ll spend your days wandering the vineyards, touring the presses and cellars, and assisting staff in making America''s favorite wine. Enjoy Tuscan-style meals served al fresco, overlooking the gorgeous countryside. Day trips include dinner in Sausalito, hiking in the redwood forests, and lunch in downtown San Francisco. ', 850, 0, 5, 'map_winecountry.gif', '\n    http://www.explorecalifornia.org/tour.php?id=26\n    '),
(11, 'Amgen Tour of California Special', 4, 'Cycle California', ' The AMGEN Tour of California is the largest cycling event in the US, over 750 miles and includes cycling world champions, Tour de France competitors, and Olympic athletes. It''s an 8-leg tour, designed to mimic the various conditions in the Tour de Trance, and Explore California has the unique pleasure of being able to offer 50 of our members spots behind the peloton, or main group of racers, on two legs of the two. This is a special, one-time only offer. Customers should be in physical and mental shape to complete this two-week ride. Be prepared to complete a detailed questionnaire about skill level and any existing health problems. ', 6000, 0, 14, 'map_northerncal.gif', '\n    http://www.explorecalifornia.org/tour.php?id=11\n    '),
(9, 'Avila Beach Hot springs', 3, 'California Hotsprings', ' Chumash have occupied Avila Beach for centuries, but it wasn''t until the late 19th century that the rest of California realized its ideal climate, proximity to the ocean and artesian springs made Avila Beach an ideal resort town. The hot springs in Avila are really unique, creating pools that hover at a natural 104 degrees, which draws aficionados from far and wide. You''ll stay at the historic Avila Hot Springs Resort, situated between oak-covered foothills that keep the morning fog away and make a natural year round air conditioner, which will enhance a nice morning, afternoon, or evening swim. This package include a two night stay in a private cabin above the springs, and a 3 day pass to the fresh water pool and 400 sq feet hot mineral pool. Optional day trips include two hour kayaking tours (we love the Cave Expedition) from Central Coast Kayaks and docent-led trips from the Point San Luis Lighthouse down the Pechos Trail. ', 1000, 0, 3, 'map_avilabeach.gif', '\n    http://www.explorecalifornia.org/tour.php?id=9\n    '),
(1, 'Big Sur Retreat', 1, 'Backpack Cal', ' The region known as Big Sur is like Yosemite''s younger cousin, with all the redwood scaling, rock climbing and, best of all, hiking that the larger park has to offer. Robison Jeffers once said, ""Big Sur is the greatest meeting of land and sea in the world,"" but the highlights are only accessible on foot. Our 3-day tour allows you to choose from multiple hikes led by experienced guides during the day, while comfortably situated in the evenings at the historic Big Sur River Inn. Take a tranquil walk to the coastal waterfall at Julia Pfeiffer Burns State Par or hike to the Married Redwoods. If you''re prepared for a more strenuous climb, try Ollason''s Peak in Toro Park. An optional 4th day includes admission to the Henry Miller Library and the Point Reyes Lighthouse. ', 750, 0, 3, 'map_bigsur.gif', '\n    http://www.explorecalifornia.org/tour.php?id=1\n    '),
(5, 'Channel Islands Excursion', 1, 'Backpack Cal', ' The Channel Islands Excursion starts with a ferry from beautiful Ventura to the nearest island in the strand, Santa Cruz. You''ll spend the day wandering the rocky coasts, sea anemone and barnacle studded shoreline, and wildflower-strewn meadows of the islands. Visit the herd of wild buffalo housed on Santa Catalina and keep an eye peeled for the endangered island fox. Take a break for lunch on Catalina in the quaint, turn of the century styled Avalon and make sure to visit the Art Deco Catalina Casino. Before ferrying home, visit the botanical gardens or climb to one of the islands'' high points and do some inexpensive whale watching. Blue whale season extends the late spring through summer months. (The Whaling Tour, run by Island Packers, is also available for an additional cost.) ', 150, 0, 1, 'map_channel.gif', '\n    http://www.explorecalifornia.org/tour.php?id=5\n    '),
(20, 'Coastal Experience', 7, 'Nature Watch', ' For 25 years, the Monterey Bay Aquarium has aspired to protect oceans for future generations by inspiring young and old with the oceans'' beauty and wonder. Explore California''s Coastal Experience Tour takes you on a behind the scenes tour of this world famous aquarium and then on a jaunt farther south to another aquatic eco-system, the Channel Islands. At the aquarium, take a private tour and learn how the tanks are maintained, watch feedings, view the newest specimens before they are available for public view and interact with the staff. Afterwards, enjoy the rest of the exhibits, like the Secret Lives of Seahorses, and visit the shark tank, the sea otter habitat, and the kelp forests. Next, hop on a cruise from Monterey to the Channel Islands. The boat docks outside Santa Barbara and you''ll take a small ferry to the islands. Try snorkeling in the reefs, or take a whale watching side trip and experience the life aquatic a natural. ', 1500, 0, 4, 'map_monterey.gif', '\n    http://www.explorecalifornia.org/tour.php?id=20\n    '),
(13, 'Cycle California: My Way', 4, 'Cycle California', ' Cycling is a fantastic way to see California and Cycle California: My Way is a customizable package that celebrates that fact. Guided and unguided routes are available and, as with all our packages, we tailor the outings to your comfort and skill level. This is a great package for families who want to see California outside of a car (and traffic!). The most popular variety is the 6-day Montery to Santa Barbara tour but this year only, we''re also offering a special package that allows serious cyclists to follow behind a competitor in the AMGEN bike race, a race that mimics the conditions in the Tour de France. Spots are limited so call now to reserve your seat! Choose your level of experience, desired distance, and location and we''ll give you a call back to plot your route and confirm your reservation. ', 1200, 0, 0, 'map_various.gif', '\n    http://www.explorecalifornia.org/tour.php?id=13\n    '),
(6, 'Day Spa Package', 2, 'California Calm', ' The Day Spa Package: it''s all in the name. One day, one spa, but not just any day or any other spa. The Ojai Valley Inn and Spa is recognized by Trip Advisor as the World'' #1 spa and among the top 10 by USA Today. Your day of relaxation starts with a kuyam, a treatment combing cleansing desert clay, dry heat, inhalation and Chumash guided meditation. Choose from among several massage services, from Swedish to deep tissue, and body treatments, including the refreshing Pixie Tangerine and Pomegranate Scrub. Finish with a lavender manicure and pedicure or a "gentleman''s facial." Couples can enjoy joint massages, and expectant mothers should treat themselves to one of the nurturing prenatal treatments. In total, the package includes 5 straight hours of treatments, reserving time for a delicious spa lunch and time to linger by one of the many pools. This day will be one you think of for weeks. ', 550, 0, 1, 'map_ojai.gif', '\n    http://www.explorecalifornia.org/tour.php?id=6\n    '),
(18, 'Endangered Species Expedition', 7, 'Nature Watch', ' Taking a cue from the Nature Conservancy, we''ve selected 15 state parks and preserves that are shining examples of conservation in action. Just one example is the Guadalupe-Nipomo Dunes Preserve, 18 miles of Earth''s most biodiverse coastal dune-lagoon ecosystem. Activities include camping, hiking, horseback riding, boating and bird watching. The tour package includes 2 nights of camping and 3 days admission to the park of your choice. We can also arrange for RV rentals. This is a great package for families who want to pass down a great experience and an education to the next generation, while participating in preserving a part of their future. ', 600, 0, 3, 'map_various.gif', '\n    http://www.explorecalifornia.org/tour.php?id=18\n    '),
(19, 'Fossil Tour', 7, 'Nature Watch', ' Hunting for trilobites? Searching for prehistoric shark teeth? We can show you where to find them! The Fossil Tour explores not just the history, but the ancient past of what we know as California. In our own backyard, we have access to a fossil record hundreds of millions of years old. Trilobites are extinct marine arthropods (think lobster) that lived in the part of the Pacific that is now the Mojave Desert. With an experienced hunter, you''ll be bussed out to search for these little desert "crabs" and visit the Calico City dig, site of a disputed findings of early man living in California to 100,000 years go. Paleontology buffs will be fascinated by the remains of this dig, presided over by none other than Louis Leaky himself. Enjoy an "on the dig" meal and then return to Los Angeles for a night at the Cinema Suites bed and breakfast, a short walk from the world famous La Brea Tar Pits. Spend the second day touring the museum''s fossil collection, watch archeologists at work, an wonder at the still active pits of tar that trapped and preserved hundreds of animals. After this tour, you''ll start to wonder what you can uncover in your own backyard! ', 500, 0, 2, 'map_various.gif', '\n    http://www.explorecalifornia.org/tour.php?id=19\n    '),
(25, 'Hot Salsa Tour', 9, 'Taste of California', ' The Hot Salsa Tour is scheduled around the preeminent salsa event in the country, the annual Oxnard Salsa Festival. Enjoy spicy food, hot music and Oxnard''s cool ocean breezes in this two-day celebration of everything salsa - the food, the music and the dance. Enjoy salsa tasting from dozens of competitors- or enter your own concoction in the amateur competition. Flavors range from fresh and fruity, hot and smoky, sweet and spicy. Shop from dozens of boutique vendors. Take a seat, or shake a leg, in front of three stages, featuring everything from jazz bands to rockabilly. The second day you''ll really be prepared to tango, after taking an evening salsa lesson from the Arthur Murray Dance Studio. If things get too hot, you can cool your heels at the luxurious Mandalay Beach Hotel and Resort and refresh yourself by the pool or take advantage of the private beach access. This yearly special is something no hot tamale wants to miss! ', 400, 0, 3, 'map_southerncal.gif', '\n    http://www.explorecalifornia.org/tour.php?id=25\n    '),
(8, 'Huntington Library and Pasadena Retreat Tour', 2, 'California Calm', ' This package is a rewarding for the mind and the soul. Visit the grounds of the incredible Huntington Library and Gardens, with over 200 acres of roses, waterways, cactus gardens and other exotic species. Have lunch in the famous Tea Room and then go inside the fabulous Art Deco buildings to survey the art collection. Afterwards, visit the Beauty Bar''s Pasadena location and enjoy a meal and drinks while having your nails buffed and your feet soaked. ', 225, 0, 1, 'map_pasadena.gif', '\n    http://www.explorecalifornia.org/tour.php?id=8\n    '),
(2, 'In the Steps of John Muir', 1, 'Backpack Cal', ' John Muir famously walked from San Francisco to Yosemite, an astounding 300 miles, and this tour is designed to trace his steps-- at least part of the way. This tour is not for the faint of heart though. This is a true backpacker''s adventure, 37 miles in 3 days. Along the way, you''ll bear witness to the classic monuments of Yosemite, such as Vernal Falls, Nevada Falls, Half Dome, Cathedral Peak, Tuolumne Meadows and Mt. Lyell. At Nevada Falls, the trail becomes narrow and from then on, you''ll be privy to a ""secret"" Yosemite, including a rarely seen face of Half Dome. John Muir Trail tickets are required- and hard to come by- but Explore California has you covered. We''ll also provide a checklist so that you come prepared with the right equipment and a seasoned guide for your tour. ', 600, 0, 3, 'map_yosemite.gif', '\n    http://www.explorecalifornia.org/tour.php?id=2\n    '),
(16, 'Joshua Tree: Best of the West Tour', 5, 'From Desert to Sea', ' "Joshua Tree: Best of the West Tour is a day-long adventure through this grandiose national park and a snippet of wild west history from the back of an open-air all-terrain vehicle. This is a great opportunity for photo hunters to shots of the coyotes, eagles and Big Horn sheep native to the area. Multiple stops includes a visit to the Rock Gardens, a 200 million year old legacy of the San Andreas Fault. The tour stops last at Pioneertown, originally built as a motion picture set in the 1940s, but has since becomes part of California''s history in its own right, as a living signpost of our fascination with the legends of the Wild West. Enjoy mesquite smoked barbeque and marvel at the ""bullet holes"" and functional hitching posts. The tour ends with a stop at Sunset Point, where on a clear day, you can see all the way to Mexico. " ', 150, 0, 1, 'map_southerncal.gif', '\n    http://www.explorecalifornia.org/tour.php?id=16\n    '),
(17, 'Kids L.A. Tour', 6, 'Kids California', ' The Island of the Blue Dolphins Tour starts with a ferry from beautiful Ventura to the Channel Islands, home of the "Lone Woman of San Nicolas Island," who was the inspiration for the Newbery Medal winning children''s book. Your Island Packers ferry guide will point out local fish and fauna, and the right time of year, you might even catch a glimpse of a dolphin or a blue whale. Once onshore, hike and look out for the herd of wild buffalo housed on Santa Catalina. Also keep an eye peeled for the endangered island fox. Enjoy a kid-friendly picnic lunch prepared by the Avalon Beach Cafe at the botanical gardens or climb to one of the islands'' high points and survey the California coast from the perspective of the heroine. On the trip back to land, the ferry stops in Santa Barbara, and you''ll have the chance to visit the famous mission where Karana lived after being rescued. One last stop for salt taffy and knick knacks at the pier and the ferry will deliver you safely back to Ventura, with your own copy of the book to take home and read as a family. ', 200, 0, 1, 'map_losangeles.gif', '\n    http://www.explorecalifornia.org/tour.php?id=17\n    '),
(21, 'Mammoth Mountain Adventure', 8, 'Snowboard Cali', ' The Mammoth Mountain Adventure is 4 days of wild, winter fun. Take a lesson the first day from the Ski and Snowboard School, led by grizzly pro instructors. This tour includes a 4 full day lift pass, so when you''re ready, you can take on any one of the 150 trails over Mammoth''s epic terrain. Equipment rentals are included, so you can pack light. Need a break? Take a scenic gondola to the summit of Mammoth Mountain, 11,000 feet in all, or take a Snowcat tour of the backcountry. Enjoy dinners at the Mammoth Mountain Inn, a snowball''s throw from the main lodge, where you''ll also be provided 3 night''s complimentary lodging. This package is available October through early June, but lift tickets are rare, so book now. ', 800, 0, 4, 'map_mammoth.gif', '\n    http://www.explorecalifornia.org/tour.php?id=21\n    '),
(10, 'Matilija Hot springs', 3, 'California Hotsprings', ' Matilija Hot Springs has long been known to locals in this small community as a place to take a hot midnight dip in the middle of winter or a leisurely summer day, leaping between the sulfur pools and the cold creek nearby. Matilija Sanctuary, however, contains private springs that can only be accessed by special guests, including members of Explore California. Choose from a 3 or 4 day stay. Besides the complimentary nightly fireside music and the on-site crafts lodge other activities include day trips to downtown Ojai for shopping in it''s Spanish revival style arcade and hiking in the East End, an Eden-esque experience if we''ve ever had one. ', 1000, 0, 3, 'map_ojai.gif', '\n    http://www.explorecalifornia.org/tour.php?id=10\n    '),
(15, 'Mojave to Malibu', 5, 'From Desert to Sea', ' Only experienced road hogs need apply! The tour group will meet at Old Glory Motorcycle Company in Lancaster, CA to retrofit and get ready for the day''s ride. The pack takes the Angeles Crest Highway, through Angeles National Forest, stopping at biker-friendly Newcomb Ranch for drinks and grub. Winding your way down through L.A., you''ll take a side trip through Griffith Park, home of the observatory and that classic scene from Rebel without a Cause. After cruising Hollywood Boulevard, the tour makes its way through Santa Monica, through Topanga Canyon and ends in Malibu, where you can grab world-class seafood and burgers from the roadside diner, Paradise Cove Beach Cafe. ', 200, 0, 1, 'map_southerncal.gif', '\n    http://www.explorecalifornia.org/tour.php?id=15\n    '),
(12, 'Monterey to Santa Barbara Tour', 4, 'Cycle California', ' This tour takes you along the best spots on the California coastline, including overnight stops in Carmel, Big Sur, San Luis Obispo, Lompoc and Santa Barbara. Cyclists of all abilities can join this scenic tour of the Pacific coast. Side trips include the famous 17 Mile Drive in cypress studded Carmel, and visits to wineries around Paso Robles and Solvang, many featured in the movie Sideways. If you tire along the way, take a break in one of our luxury equipped companion cars, which follows riders along every leg of the trip. Dine with the group or request private reservations at any one of the fining dining spots our reservationists recommend. Private accommodations are provided for the overnight stays. Breaks before and after lunch provide plenty of time for sightseeing and shopping. ', 2500, 0, 6, 'map_various.gif', '\n    http://www.explorecalifornia.org/tour.php?id=12\n    '),
(22, 'Mountain High Lift-off', 8, 'Snowboard Cali', ' Mountain High is only an hour from Los Angeles, but once you arrive, you''ll feel like you''re in another world. The Mountain High Lift-off is the weekender''s ski spectacular, perfect for couples who need a retreat, featuring two days of premium runs with an all access Express Lift ticket, available exclusively through Explore California. No more waiting in line and guaranteed admittance even when the resort sells out. Accommodations are provided at the Larks Nest Cabin, a vintage charmer featuring a stone fireplace, clawfoot tub, and full kitchen. Dine at the Wrightwood Inn''s cozy mountain pub, or grab a sandwich from the Evergreen Cafe and Raccoon Saloon. Equipment rental and transportation from Los Angeles International Airport is included. ', 800, 0, 3, 'map_southerncal.gif', '\n    http://www.explorecalifornia.org/tour.php?id=22\n    '),
(23, 'Olive Garden Tour', 9, 'Taste of California', ' Ojai Olive is a small, family-run olive orchard, which has been pressing their own special, fragrant olive oil for over 10 years. Immerse yourself in this ancient practice, which is both an art and an edible. The Ojai Olive tour offers begins outside with the history of the grove, an explanation of the olive varieties, their maturing process, the harvesting, a visit to the tree nursery, and more. They then take you inside the barn and explain the process of making the olive oil. Lastly, stop in the tasting room and find out how different curing and separation processes can result in such unique flavors: citrus, hints of pepper, grass. Take a break with a picnic lunch provided by Azu restaurant, makers of authentic Spanish style tapas with a California flair. Included are brioche with olive tapenade, featuring black and green olives from Ojai Olive and prepared by the chef especially for this tour. ', 75, 0, 1, 'map_ojai.gif', '\n    http://www.explorecalifornia.org/tour.php?id=23\n    '),
(24, 'Oranges and Apples Tour', 9, 'Taste of California', ' Oak Glen is a tiny hamlet located in the foothill of the San Bernadino Mountain, only 90 minutes from LA, but the climate makes it perfect for stone fruits, such as pears, peaches, and nectarines. However, the jewel of this town is the apple. You''ll start the day at Riley''s Apple Farm, where you can pick and press as many apples as you can carry. Take a hayride around the farm property and, a fun treat for kids, visit the barn animals. Feast on apple-wood smoked BBQ featuring tri-tip, ribs and chicken apple sausage. Lodging is provided at the quaint Craftin Hills Inn. The next day, it''s a short backwoods drive to Ojai, CA, where you''ll receive a private tour and picnic lunch at the Churchill Brenneis Orchard. Owners Jim Churchill and Lisa Brenneis are knowledgeable and warm, and you''ll leave with a glow and the most delicious tiny tangerines you''ve ever tasted. Spend a restful night at the Lavender Inn in beautiful downtown Ojai before returning to the regular pace. ', 350, 0, 3, 'map_southerncal.gif', '\n    http://www.explorecalifornia.org/tour.php?id=24\n    '),
(7, 'Restoration Package', 2, 'California Calm', ' California is no stranger to luxury (think Rodeo Drive) but we also offer a myriad of ways to not only pamper the body, but the spirit as well. Choose from among 3 options designed to help you relax and restore in the Restoration Package. Reconnect with nature and with yourself at the San Juan Spa, our Orange County Oasis; go backwoods, literally, on our Yosemite Yoga Retreat; or take comfort in our Napa Valley Validation spa sessions. Perfect for couples, the tireless mother or father you want to thank, or just yourself, this tour will immerse you in serenity. ', 900, 0, 2, 'map_various.gif', '\n    http://www.explorecalifornia.org/tour.php?id=7\n    '),
(3, 'The Death Valley Survivor''s Trek', 1, 'Backpack Cal', ' This 2 day, 1 night tour takes you deep into the heart of Death Valley National Park. Due to extreme temperatures (120 degrees and higher) in the summer months, this tour is only offered November through April. This overnighter is no picnic though. Our guide will lead you on a 12 mile, off-trail hike down Death Valley Wash and into the backcountry for an overnight, hard terrain camping. Luckily, 12 miles takes you out of range of almost any city lights, something that draws thousands of star gazers to Death Valley ever year. If you can survive the 12 miles back, take advantage of the location to stop in at Scotty''s Castle, a genuine castle built by the eccentric and wealthy Walter Scott for his wife. This tour will make you truly appreciate modern luxuries. ', 250, 0, 2, 'map_valley.gif', '\n    http://www.explorecalifornia.org/tour.php?id=3\n    '),
(4, 'The Mt. Whitney Climbers Tour', 1, 'Backpack Cal', ' Backpackers and hikers taking the Mt. Whitney Climbers Tour won''t need hooks and rappelling gear, but they will need to be on the look out for majestic sunrises, giant granite peaks and everything from brown bears to marmots. You''ll approach the towering peak from the trailhead on the western face, starting 6,000 feet above sea level. The Mt. Whitney Trail extends 11 miles and another 8 feet up to the peak. While no expensive training is required, you''ll still need planning, permits, and preparation. Explore California will set you up with a trail permit, a two night camping pass, and an expert guide. We''ll also help outfit you with the correct gear and make sure you are prepared for the length and elevation gain of the climb. ', 650, 0, 4, 'map_whitney.gif', '\n    http://www.explorecalifornia.org/tour.php?id=4\n    ');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
